module.exports = [{
  filePath: '/Users/ingrid/src/ember-cli-detergent/test-fixtures/bad/bad.js',
    messages:
     [ { ruleId: 'disallowMethods',
         severity: 2,
         message: 'foo',
         line: 1,
         column: 1,
         nodeType: 'CallExpression',
         source: 'blah.foo(1);' },
       { ruleId: 'disallowMethods',
         severity: 2,
         message: 'foo',
         line: 2,
         column: 1,
         nodeType: 'CallExpression',
         source: 'blah.foo(3);' },
       { ruleId: 'disallowMethods',
         severity: 2,
         message: 'boo',
         line: 3,
         column: 1,
         nodeType: 'CallExpression',
         source: 'blah.boo(1);' },
       { ruleId: 'disallowMethods',
         severity: 2,
         message: 'boo',
         line: 4,
         column: 1,
         nodeType: 'CallExpression',
         source: 'blah.boo(1);' },
       { ruleId: 'disallowMethods',
         severity: 2,
         message: 'boo',
         line: 5,
         column: 1,
         nodeType: 'CallExpression',
         source: 'blah.boo(1);' } ],
    errorCount: 5,
    warningCount: 0,
    source: 'blah.foo(1);\nblah.foo(3);\nblah.boo(1);\nblah.boo(1);\nblah.boo(1);\n'
}];
